### PR TITLE
Fixed unittest collection with @async_to_sync on Python 3.7.

### LINKED ISSUE #103: Python 3.7: @async_to_sync unittest collection error.
On macOS (not sure about others yet) with Python 3.7.2. 

1. Create a new venv and install `asgiref`. 
2. Create a `tests.py` file: 

```python 
import unittest

from asgiref.sync import async_to_sync


class ASGITest(unittest.TestCase):

    @async_to_sync
    async def test_wrapped_case_is_collected(self):
        self.assertTrue(True)
```

3. `python -m unitest tests.py`

## Output

```
(tmp-68415466ed791e9) ~/ve/tmp-68415466ed791e9 $ python -m unittest issue/tests.py
Traceback (most recent call last):
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/main.py", line 159, in createTests
    self.module)
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/loader.py", line 124, in loadTestsFromModule
    tests.append(self.loadTestsFromTestCase(obj))
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/loader.py", line 90, in loadTestsFromTestCase
    testCaseNames = self.getTestCaseNames(testCaseClass)
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/loader.py", line 235, in getTestCaseNames
    testFnNames = list(filter(shouldIncludeMethod, dir(testCaseClass)))
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/loader.py", line 232, in shouldIncludeMethod
    fullName = '%s.%s' % (testCaseClass.__module__, testFunc.__qualname__)
AttributeError: 'functools.partial' object has no attribute '__qualname__'
```

**This works with Python 3.6.8.** 

I want to pin down ~~if it's just macOS, and~~ what change in Python triggers it, but opening now to see if people can test on their setup and/or have any thoughts. 

Ran into this running the Django test suite (on Django `master`) against Python 3.7.2. 

**Update**: failing test casefor Python 3.7  (and fix) in #104.

### PR DESCRIPTION
**Pull request by carltongibson**
Closes #103. 

Test case reproducing issue locally. Passes on py36. Fails on py37. Seeing how it goes on Travis. 

Update: fix added.

### CODE REVIEW

**Comment by carltongibson** [comment]
And fails on Python 3.7 on Travis too (so it's not macOS...)

**Comment by carltongibson** [comment]
Setting the missing attribute _fixes_ the issue. Q: Do we need to be more defensive here? (Not sure currently.)

File: asgiref/sync.py [hunk 1]
```diff
@@ -82,7 +82,9 @@ def __get__(self, parent, objtype):
         """
         Include self for methods
         """
-        return functools.partial(self.__call__, parent)
+        func = functools.partial(self.__call__, parent)
+        func.__qualname__ = self.awaitable.__qualname__
```
Comment (davidism) [inline asgiref/sync.py]: I'm not sure about the design of `partial`, but it might be better to guard this with `if not hasattr(func, "__qualname__")` or similar, in case a future version of Python fixes/changes it.

**Comment by carltongibson** [comment]
From https://bugs.python.org/issue34475, the correct approach is to use `functools.update_wrapper()` to mimic the relevant `__name__`, `__module__` and **here** `__qualname__` attributes. (Presumably that provides the relevant error handling.) Updated accordingly.

File: asgiref/sync.py (hunk 1 above)
Comment (carltongibson) [reply asgiref/sync.py]: Thanks @davidism, see [other comment](https://github.com/django/asgiref/pull/104#issuecomment-509353970) for new/better/recommended approach.

**Comment by andrewgodwin** [comment]
Looks good, and yet again another case where I should have sought out `functools` straight away.

**Comment by carltongibson** [comment]
Hey @andrewgodwin. It looks like the underlying error was a regression in Python 3.7.0, which was fixed for 3.7.3. 

https://bugs.python.org/issue35767

SO, on latest Pythons this works without the `update_wrapper()` call. 

Not sure if you'd still want to patch it or not? 

(Sorry for the last-minute update: it was passing on DjangoCI, which was running 3.7.3 so I had a _¿Que?_ moment.)

**Comment by andrewgodwin** [comment]
I think it's still worth keeping it in, because it is the Right Way to do things.

**Comment by carltongibson** [comment]
Hey @andrewgodwin. Can I be a pain and ask you to release this please? 

Just found a prospective Django contributor who's bumped into it trying to get started and ... well... — it would be better if Django's test suite _Just Worked™_ 🙂 (If there's one person reaching out, I'm guessing there's several hitting the same issue.)

Thanks! 🏅

**Comment by andrewgodwin** [comment]
Sure thing, just released `3.2.0`. I had sort of forgot it had a crucial bugfix in it - my bad!

**Comment by carltongibson** [comment]
No problem. Thank you Andrew!
