### ISSUE TITLE
Python 3.7: @async_to_sync unittest collection error. 

### ISSUE THREAD

**Issue by carltongibson** [django/asgiref#103]
On macOS (not sure about others yet) with Python 3.7.2. 

1. Create a new venv and install `asgiref`. 
2. Create a `tests.py` file: 

```python 
import unittest

from asgiref.sync import async_to_sync


class ASGITest(unittest.TestCase):

    @async_to_sync
    async def test_wrapped_case_is_collected(self):
        self.assertTrue(True)
```

3. `python -m unitest tests.py`

## Output

```
(tmp-68415466ed791e9) ~/ve/tmp-68415466ed791e9 $ python -m unittest issue/tests.py
Traceback (most recent call last):
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/main.py", line 159, in createTests
    self.module)
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/loader.py", line 124, in loadTestsFromModule
    tests.append(self.loadTestsFromTestCase(obj))
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/loader.py", line 90, in loadTestsFromTestCase
    testCaseNames = self.getTestCaseNames(testCaseClass)
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/loader.py", line 235, in getTestCaseNames
    testFnNames = list(filter(shouldIncludeMethod, dir(testCaseClass)))
  File "/Users/carlton/.pyenv/versions/3.7.2/lib/python3.7/unittest/loader.py", line 232, in shouldIncludeMethod
    fullName = '%s.%s' % (testCaseClass.__module__, testFunc.__qualname__)
AttributeError: 'functools.partial' object has no attribute '__qualname__'
```

**This works with Python 3.6.8.** 

I want to pin down ~~if it's just macOS, and~~ what change in Python triggers it, but opening now to see if people can test on their setup and/or have any thoughts. 

Ran into this running the Django test suite (on Django `master`) against Python 3.7.2. 

**Update**: failing test casefor Python 3.7  (and fix) in #104.
